### ISSUE TITLE
Returns NULL when string is present?

### ISSUE THREAD

**Issue by beave** [RaphaelJ/fast_strstr#6]
Hello, 

I've been testing fast_strstr for a project.   In my testing,  I ran into something really strange.  It's likely something I'm doing wrong. Here my simple test:

--<snip>--
char *string1 = "one string two.";
char *string2 = "this one string two";

printf("String 1: |%s|\n", fast_strstr(string1, "string"));
printf("String 2: |%s|\n", fast_strstr(string2, "string"));
--<snip>--

Results:

--<snip>--
String 1: |string two.|
String 2: |(null)|
--<snip>--

Any ideas what I'm doing wrong here?  I expect result #1, but result #2 is strange to me.  

I'm using the code from github cloned today.

**Comment by beave** [comment]
Side note: 

Tested on a Linux box (gcc-4.6.3) and OSX (clang-503.0.40).  Same results.

**Comment by kirabou** [comment]
@beave, if you change "unsigned int  sums_diff     = *haystack;" (line 72) with "int sums_diff = 0;" it should work as expected. sums_diff can be a negative value because it is a difference between two integers, so  it must no be declared as unsigned. And it must be initialized to zero or the first character in *haystack is counted twice.

**Comment by beave** [comment]
Thank you for the response!

**Comment by TSlivede** [comment]
No, the correct fix for this bug should be:
```
unsigned int sums_diff = *haystack - *needle;
```
keeping it unsigned is ok, because unsigned has a well defined overflow/underflow behavior. Changing it to signed will could instead cause a bug (although very unlikely) if the needle is large enough that alone from summing over the needle a value bigger then int_max is reached.

And it should not be initialized to 0 but to this difference, because in the later loop the calculation of the sum starts at index 1 not 0.

**Comment by TSlivede** [comment]
Oh, and please reopen the issue until a correct fix is actually merged.
